### PR TITLE
Seurat

### PR DESCRIPTION
**Pull request by NaomiBreslin**
Updated data ingest using the Seurat pipeline. This script needs to be checked and updated if necessary.
Please refer to the comments if any of the script is unclear.
Bug with dimplot for umap since Seuat v4 was released.

### CODE REVIEW

**Review by marcellp — DISMISSED** [review]
lgtm

**Comment by ivababukova** [comment]
Do not merge - the script is not working end to end - uploading the anndata part is raising an error

**Comment by marcellp** [comment]
> Do not merge - the script is not working end to end - uploading the anndata part is raising an error

Can you show me what the error is exactly @ivababukova ?

**Review by marcellp — CHANGES_REQUESTED** [review]
Comments by @ivababukova should be addressed before merging.

**Comment by NaomiBreslin** [comment]
> Comments by @ivababukova should be addressed before merging.

It runs end to end with no errors. There was errors previously when it was ran on the cluster but works fine when run locally.

**Pull request closed without merging**
